spring:
  bot:
    plugin-list: # 配置插件列表（有序），如果插件返回0，继续执行剩余插件，如果插件返回1，终止剩余插件执行
      - net.lz1998.pbbot.plugin.LogPlugin # 日志插件
      - net.lz1998.pbbot.plugin.DemoPlugin # 测试插件
      - net.lz1998.pbbot.plugin.ImagePlugin # 动态生成图片插件
      - net.lz1998.pbbot.plugin.HelloPlugin # 测试插件
  datasource:
    username: root
    password: zsx.2468
    url: jdbc:mysql://43.143.69.67:3306/game?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 1200000
server:
  port: 8081